# Generated by Django 4.2.13 on 2024-05-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ("-created_at",)},
        ),
    ]
