# Generated by Django 4.2.13 on 2024-05-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_options_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="blog/default.jpj", upload_to="blog/"),
        ),
    ]
