# Generated by Django 4.2.13 on 2024-05-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(to="blog.category"),
        ),
    ]
