# Generated by Django 4.2.13 on 2024-06-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_comment_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="post",
            name="login_require",
            field=models.BooleanField(default=False),
        ),
    ]
